[build]
command = "ng build --configuration=production && ng run serenity-spot:server:production"
publish = "dist/serenity-spot/browser"
functions = "dist/serenity-spot/server"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
